algoritmo "Converter °C em °F"
//Disciplina : LOPAL (Lógica de Programação)
//F9 (executa meu código)

//Autor: Maria Eduarda Vilela
//Data: 13/04/2026
var
//Declaração de variáveis
grausC, grausF : real

inicio
// Entrada de dados
   escreva ("Digite a temperatura em °C: ")
   leia  (grausC)
   
//Converção para °F
            grausF <- 9 * grausC / 5 + 32

//Exibir dados
         escreval ("Essa temperatura em °F é igual a ", grausF)
fimalgoritmo
